packages/eslint-config-acb-react-typescript/package-lock.json
Lerna unfortunately didn't generate a `package-lock` last time `npx lerna bootstrap` was run, so here it is
=> chore: add missing package lock

packages/eslint-config-ts-react/index.js, packages/eslint-config-ts-react/package-lock.json, packages/eslint-config-ts-react/package.json, packages/eslint-config-ts-react/rules/react.js, packages/eslint-config-ts-react/rules/typescript.js, packages/eslint-config-ts/.eslintrc, packages/eslint-config-ts/LICENSE.md, packages/eslint-config-ts/README.md, packages/eslint-config-ts/index.js, packages/eslint-config-ts/package-lock.json, packages/eslint-config-ts/package.json, packages/eslint-config-ts/rules/style.js, packages/eslint-config-ts/rules/typescript.js
This extracts the non-React Typescript settings from `eslint-config-ts-react` to a new package.
Also replaces the `eslint-config` dependency in `eslint-config-ts-react` with the new repo.
I had to export `packages/eslint-config-ts/rules/style.js` so it can be accessed in `packages/eslint-config-react/rules/react.js`. Pls let me know if you have a better idea on how to do this
=> Add typescript eslint config

packages/css-module-bem-loader/lib/transform.js
prevents warning when a css module has no block level styles
=> fix: prevent misleading warning

.editorconfig, packages/eslint-config-react/rules/react.js, packages/eslint-config-ts-react/rules/react.js
* removes preference from `.editorconfig`
* replaces `react/jsx-indent`, as well as `react/jsx-indent-props` with tabs instead of spaces
=> chore: adjust rules for using tabs instead of spaces

packages/eslint-config-react/rules/react.js, packages/eslint-config-ts-react/rules/react.js
Seems this should be added through `extends` and not `plugins` - however adding this results in `Error: Cannot find module 'plugin:react/jsx-runtime'`.
After checking the configuration it seems our current configuration should cover everything from the plugin either way, so it should be ok to remove it completely
=> chore: remove plugin react jsx runtime

packages/eslint-config-ts-react/package.json
The outdated peer dependency version didn't take `eslint 7` into account, so newer versions of `npm` would throw an error when installing the package
Closes #30
=> fix: update peer dependency version

lerna.json
From the docs:
>If the message contains %s, it will be replaced with the new global version version number prefixed with a "v". If the message contains %v, it will be replaced with the new global version version number without the leading "v". Note that this placeholder interpolation only applies when using the default "fixed" versioning mode, as there is no "global" version to interpolate when versioning independently.
This removes the version from the commit message written by Lerna on publish
=> chore: remove version from publish commit message

packages/stylelint-config-property-sort-order/package-lock.json, packages/stylelint-config-property-sort-order/package.json
Previous version of `stylelint-config-property-sort-order-smacss` doesn't seem to have node 16 defined in `engines` - the latest version should fix this
=> chore: update stylelint-config-property-sort-order-smacss version

packages/stylelint-config-property-sort-order/package-lock.json
This deletes `stylelint-config-property-sort-order`'s `package-lock.json` and runs a fresh install with npm 6.
Hopefully fixes the issues with external dependencies of internal dependencies we've encountered lately -`package-lock.json` looks better already.
If this works after publishing, I will update `engines.npm` of the root `package.json`, and also update `README.md` in the next PR
=> chore: reinstall stylelint-config-property-sort-order with npm 6

packages/stylelint-config-property-sort-order/package-lock.json, packages/stylelint-config-property-sort-order/package.json, packages/stylelint-config/package-lock.json, packages/stylelint-config/package.json
Updates [stylelint-config-property-sort-order-smacss](https://github.com/cahamilton/stylelint-config-property-sort-order-smacss/releases/tag/v8.0.0) to v8 and [stylelint-config-recommended](https://github.com/stylelint/stylelint-config-recommended/releases/tag/6.0.0) to v6 to add support for Stylelint v14. Currently cannot update Stylelint on the Elsewhere project because of the peer dependencies on Stylelint v13.
Regarding version bumping would this be a minor (2.2.0) or a major (3.0.0) bump?
=> Add support for Stylelint v14

package-lock.json, packages/eslint-config-ts/index.js, packages/stylelint-config-property-sort-order/package-lock.json, packages/stylelint-config-property-sort-order/package.json, packages/stylelint-config/package-lock.json
Updates our Stylelint config dependencies ([stylelint-config-property-sort-order-smacss](https://github.com/cahamilton/stylelint-config-property-sort-order-smacss#stylelint-config-property-sort-order-smacss) and [css-property-sort-order-smacss](https://github.com/cahamilton/css-property-sort-order-smacss)) to include sort order for [logical properties](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties).
=> Update Stylelint config SMACSS to 2.2

packages/stylelint-config/LICENSE.md, packages/stylelint-config/README.md, packages/stylelint-config/index.js, packages/stylelint-config/package-lock.json, packages/stylelint-config/package.json
**Description**
This PR simplifies the configuration of the property sort order, and also upgrades the other config component of [stylelint-config-recommended](https://github.com/stylelint/stylelint-config-recommended).
**Context**
Previously, we relied on another package, [stylelint-config-property-sort-order](https://github.com/acolorbright/acb-tools-and-configs/tree/main/packages/stylelint-config-property-sort-order), to enforce newlines between the SMACSS property groups. This is now possible to configure directly in our Stylelint configuration (after installing the underlying [stylelint-order](https://github.com/hudochenkov/stylelint-order) dependency directly), which I have done here. This means that we can deprecate the `stylelint-config-property-sort-order` package after this is …
=> Simplify and upgrade Stylelint config

packages/eslint-config/package.json, packages/eslint-config/rules/extras.js
Uses https://github.com/mizdra/eslint-plugin-layout-shift to make width and height attributes required for `img` elements. Still not sure if it's possible to test this before publishing, so it might be best to just check the package docs for now.
=> Forbid img elements without width and height attributes

packages/eslint-config-react/package-lock.json, packages/eslint-config-react/rules/react.js, packages/eslint-config-ts-react/package-lock.json, packages/eslint-config-ts-react/package.json, packages/eslint-config-ts-react/rules/react.js, packages/eslint-config/package-lock.json
Removes the [`object.assign` package](https://www.npmjs.com/package/object-assign) and replace its usage with `Object.assign`:
> Node.js 4 and up, as well as every evergreen browser (Chrome, Edge, Firefox, Opera, Safari), support Object.assign() 🎉. If you target only those environments, then by all means, use Object.assign() instead of this package.
=> Remove `object.assign` package

packages/eslint-config-react/rules/react.js, packages/eslint-config-ts-react/rules/react.js
Fix issue that came up when running `npx lerna run test`:
```
Use an object spread instead of `Object.assign` eg: `{ ...foo }`  prefer-object-spread
```
=> fix: use an object spread instead of object.assign

packages/eslint-config-react/rules/react.js
Updates the `react/jsx-filename-extension` rule so that only .jsx files may have JSX
=> Only .jsx files may have JSX

packages/eslint-config-react/index.js, packages/eslint-config-react/package-lock.json, packages/eslint-config-react/package.json, packages/eslint-config-react/rules/import.js, packages/eslint-config-ts-react/rules/import.js
Adds import related rules: see https://github.com/acolorbright/base-next/pull/341
Adds [eslint-plugin-simple-import-sort](https://github.com/lydell/eslint-plugin-simple-import-sort) to `@acolorbright/eslint-config-react`. This is currently added separately in the eslint configuration of our [coding task](https://github.com/acolorbright/coding-task-next/blob/main/.eslintrc.js) and I’d prefer moving that out.
=> Update import rules

packages/eslint-config-ts-react/package-lock.json, packages/eslint-config/index.js, packages/eslint-config/package-lock.json, packages/eslint-config/package.json
Removes [`eslint-config-prettier`](https://github.com/prettier/eslint-config-prettier). In order for this to work it needs to come last:
> Make sure to put it last, so it gets the chance to override other configs.
However, we are extending the `@acolorbright/eslint-config` multiple times so we would need to repeat it in each config in order for it to work. A better approach seems to be adding this to the actual projects that we use our configs in.
=> Remove eslint-config-prettier

packages/eslint-config-react/README.md, packages/eslint-config-react/package.json, packages/eslint-config-ts-react/README.md, packages/eslint-config-ts-react/package.json, packages/eslint-config-ts/README.md, packages/eslint-config-ts/package.json, packages/eslint-config/README.md
Adds `@mizdra/eslint-plugin-layout-shift` as peer dependency where necessary. It was only listed as a peer dependency in `@acolorbriht/eslint-config`. According to ESLint’s docs:
> If your shareable config depends on a plugin, you should also specify it as a peerDependency
https://eslint.org/docs/latest/extend/shareable-configs#publishing-a-shareable-config
Also updates the README’s where necessary.
=> Add @mizdra/eslint-plugin-layout-shift as peer dependency

packages/eslint-config-react/rules/react-a11y.js, packages/eslint-config-ts-react/rules/react-a11y.js
Updates the `jsx-a11y/label-has-associated-control` rule:
- use `either` instead of `both` for `assert`
- stick with the default of `2` for `depth`
It is a bit weird to require both a `for` attribute and the `label` element wrapping. Also requiring both can result in the following issue:
The label element wraps the input. Axe is satisfied, eslint will throw an error as it wants an `htmlFor` attribute. If this is added Eslint is happy, but can’t or doesn’t check whether the input has an id that is associated with the `htmlFor` JSX attribute. Axe won’t throw an error because it sees the `label` is wrapping the `input`. By require either wrapping or the `htmlFor` attribute Axe will throw an error when the `htmlFor` is present but not associated with an `input. …
=> Update label has associated control options

packages/browserslist-config/index.js
Updates our browserslist configuration to expand browser compatibilty.
We currently have an [audience coverage of 31.7%](https://browsersl.ist/#q=last+2+chrome+versions%2Clast+2+firefox+versions%2Clast+2+safari+major+versions%2Clast+2+edge+versions%2Clast+2+iOS+major+versions%2Clast+2+android+versions%2Clast+2+samsung+versions)
This update adds Opera, Chrome for Android, Firefox for Android and adds `not dead` as it gets skipped when using last N versions:
> The not dead query skipped when using last N versions query
It also adds `not OperaMini all` as I think it makes more sense to add this browser per project if necessary.
[Audience coverage after this update becomes 73.7%](https://browsersl.ist/#q=last+2+Android+versions%2Clast+2+Chrome+versions%2Clast+2+ChromeAndroid+versions%2Clast+2+ …
=> Expand browser compatibility

package-lock.json, packages/stylelint-config/package.json
This is a patch update needed for https://github.com/acolorbright/acb-tools-and-configs/pull/142
=> Update dependency stylelint-order
